FROM ubuntu:18.04

WORKDIR /app

RUN apt-get update -y

RUN apt-get install -y python-pip python-dev

COPY ./api/requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app

CMD [ "python" , "./api/app.py" ]
