# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./sys-stats/package.json ./sys-stats/yarn.lock ./
COPY ./sys-stats/src ./src
COPY ./sys-stats/public ./public
RUN yarn install
RUN yarn build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY ./sys-stats/nginx.conf /etc/nginx/conf.d/default.conf
